### ISSUE TITLE
root login password is unknown

### ISSUE THREAD

**Issue by davidw0374** [KeitetsuWorks/EBAZ4205#1]
Thanks for your effort on this github project , the build process is smooth and it looks like the ethernet interface is up . but root login password is not "root" as normally , would you please publish the password of root account?
btw, my toolchain is petalinux v2021.2.

============
sorry ,i made a mistake, i booted from internal flash previously . now the boot sd card of your petalinux building is ok ,

**Comment by KeitetsuWorks** [comment]
> i made a mistake, i booted from internal flash previously . now the boot sd card of your petalinux building is ok

got it. I'm glad your problem has been solved.
